from pathlib import Path


FIGURES = [
    (
        "fig:architecture",
        "fig1_architecture.pdf",
        "BioRAG-DRAG architecture. Vector retrieval provides an instant multimodal candidate layer; BLAST supplies sequence verification and reranking; DRAG packages vector, alignment, text, and graph evidence into typed traces for a local biomedical agent.",
    ),
    (
        "fig:dataset",
        "fig2_dataset.pdf",
        "BioRAG-Standard v0 composition. The benchmark/library contains 257,886 retrievable records across Standard text, protein windows, DNA/cDNA windows, and mixed records, with 112 annotated retrieval tasks.",
    ),
    (
        "fig:retrieval",
        "fig3_retrieval_quality.pdf",
        "Retrieval quality on the 100-query sequence subset. BLAST remains the strongest alignment-grounded verifier, while vector retrieval provides useful candidate pools; candidate BLAST improves as the vector overfetch budget increases.",
    ),
    (
        "fig:latency",
        "fig4_latency.pdf",
        "Instant and verified retrieval latency. Vector lookup is measured after query embedding and supports an instant mode; BLAST dominates verified-mode latency, while graph expansion is negligible.",
    ),
    (
        "fig:drag_biology",
        "fig5_drag_biology.pdf",
        "DRAG biological-structure analysis. Vector, BLAST, and hybrid graphs expose different graph connectivity, functional enrichment, and literature-sharing patterns; these signals support hypothesis-generating biological evidence organization.",
    ),
]


def main():
    out = Path(__file__).resolve().parent / "latex_includes.tex"
    lines = [
        "% Auto-generated by figures/gen_latex_includes.py",
        "% Copy snippets into the LaTeX manuscript after converting paper.md.",
        "",
    ]
    for label, filename, caption in FIGURES:
        lines.extend(
            [
                "\\begin{figure}[t]",
                "    \\centering",
                f"    \\includegraphics[width=0.95\\textwidth]{{figures/{filename}}}",
                f"    \\caption{{{caption}}}",
                f"    \\label{{{label}}}",
                "\\end{figure}",
                "",
            ]
        )
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved {out}")


if __name__ == "__main__":
    main()
